### ISSUE TITLE
bug after adding a bet on a game from the game view

### ISSUE THREAD

**Issue by ezraroi** [ezraroi/MundialitoV2#143]
```
GameCtrl: Bet 1186 was added
bundle.min.js:2 TypeError: Cannot read properties of undefined (reading 'HomeTeam')
    at t.getTeamByCardsMark (app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1:11258)
    at fn (eval at compile (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:399081), <anonymous>:4:189)
    at r (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:386970)
    at l.$digest (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:394122)
    at l.$apply (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:396103)
    at lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:359303
    at C (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:362185)
    at v.onload (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:361556)
    at XMLHttpRequest.sentryWrapped (bundle.min.js:2:53392) undefined
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ angular.min.js:2
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
C @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
v.onload @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2
load
L @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
dispatch @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
g.handle @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2Understand this error
bundle.min.js:2 TypeError: Cannot read properties of undefined (reading 'HomeTeam')
    at t.getTeamByCornersMark (app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1:11134)
    at fn (eval at compile (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:399081), <anonymous>:4:191)
    at r (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:386970)
    at l.$digest (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:394122)
    at l.$apply (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:396103)
    at lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:359303
    at C (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:362185)
    at v.onload (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:361556)
    at XMLHttpRequest.sentryWrapped (bundle.min.js:2:53392) undefined
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ angular.min.js:2
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
C @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
v.onload @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2
load
L @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
dispatch @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
g.handle @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2Understand this error
bundle.min.js:2 TypeError: Cannot read properties of undefined (reading 'HomeTeam')
    at t.getTeamByCardsMark (app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1:11258)
    at fn (eval at compile (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:399081), <anonymous>:4:189)
    at r (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:386970)
    at l.$digest (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:394122)
    at l.$apply (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:396103)
    at lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:365167
    at sentryWrapped (bundle.min.js:2:53392) undefined
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ angular.min.js:2
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2
setInterval
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
t.configureTimer @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
t._onNewToast @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$emit @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
pop @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
success @ app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1
(anonymous) @ app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
C @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
v.onload @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2
load
L @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
dispatch @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
g.handle @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2Understand this error
bundle.min.js:2 TypeError: Cannot read properties of undefined (reading 'HomeTeam')
    at t.getTeamByCornersMark (app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1:11134)
    at fn (eval at compile (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:399081), <anonymous>:4:191)
    at r (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:386970)
    at l.$digest (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:394122)
    at l.$apply (lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:396103)
    at lib-min-2d5e40df8764ea1d842fca768d139b58.js:1:365167
    at sentryWrapped (bundle.min.js:2:53392) undefined
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ angular.min.js:2
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2
setInterval
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
t.configureTimer @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
t._onNewToast @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$emit @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
pop @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
success @ app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1
(anonymous) @ app-min-7650b9735dadd2976bd3e012a2ea28c6.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
C @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
v.onload @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2
load
L @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ bundle.min.js:2
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$digest @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
$apply @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
(anonymous) @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
dispatch @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
g.handle @ lib-min-2d5e40df8764ea1d842fca768d139b58.js:1
sentryWrapped @ bundle.min.js:2Understand this error
```

**Comment by ezraroi** [comment]
https://mundialito.sentry.io/issues/8293221/?project=4507975304413264&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0
